# Generated by Django 3.0.7 on 2020-07-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IC',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('protected', models.BooleanField(default=False)),
            ],
        ),
    ]
