# Generated by Django 3.0.7 on 2020-07-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ic',
            options={'ordering': ['number']},
        ),
    ]
